[tool.poetry]
name = "pyliteflux"
version = "0.1.0"
description = ""
authors = ["'fkl' <18654198191@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
